title: Premonition Demo Site
description: Demo site for Premonition
baseurl: "/premonition-demo"
url: ""

plugins:
  - jekyll-feed
  - premonition

premonition:
  types:
    warning:
      meta:
        fa-icon: fa-check-square
